### PR TITLE
fix logging actions

### LINKED ISSUE #13: Devtool is not tracking actions
Devtool is not working even in [link](https://codesandbox.io/s/lrz5wloklm) provided by the package. Clicking actions in form update the localStorage and shown in devtool but not the actions

Also tried locally with same result. 

Resetting also doesn't work. The window variable is different

### PR DESCRIPTION
**Pull request by ssuvorov**
- [x] fix to display a log of actions
Closes #13

### CODE REVIEW

**Comment by ssuvorov** [comment]
Closes #13

**Comment by ssuvorov** [comment]
@bluebill1049 not sure what to do with tests. This is my 1st contribution.

**Comment by bluebill1049** [comment]
Let's get it in! Thanks @ssuvorov i will pass you a beta.

**Comment by bluebill1049** [comment]
`little-state-machine-devtools@1.0.0-beta.5`

**Pull request merged**
